name: Build docker image and test
on:
  pull_request:
env:
  IMAGE_NAME: opensafely-proxy
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
    - name: Build image
      run: just build
    - name: Run tests
      run: just test
