name: Build docker image and test
on:
  pull_request:
env:
  IMAGE_NAME: opensafely-proxy
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
    - name: Build image
      run: just build
    - name: Run tests for opensafely.org
      run: just test opensafely.org
    - name: Run tests ted.bennettoxford.org
      run: just test ted.bennettoxford.org
