name: Build docker image and test
on:
  pull_request:
env:
  IMAGE_NAME: opensafely-proxy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
    - name: Build image
      run: just build
    - name: Run tests
      run: just test
